### PR TITLE
Use task colour (#59), Hide non-working days (#9, #57), See all team …

### LINKED ISSUE #9: Hide Days?
Is there a way to hide weekends?  Or even better could the calendar only show days that are configured as working days in TFS?

Thanks for your help, we love this extension and use it daily!!

### LINKED ISSUE #57: Revision
Good day. We are delighted with the presentation. We really want to add the following to the presentation: - the ability to filter by artist; - the ability to hide weekends; - there is not enough filter by User Story (hide tasks that are in the queue or, on the contrary, are completed) Consider suggestions for refinement?

### LINKED ISSUE #59: Bugs are yellow
When working with bugs as tasks on a board, they still show up as yellow in the drop plan schedule. Any way they could be made red?

### LINKED ISSUE #73: Not able to view all the resources who are part of the sprint
Is there any way I can view all the resources who are part of the sprint. I guess currently the only resources are displayed who are assigned with some or the other task. Please advise.

### LINKED ISSUE #111: Wrong Hours Capacity
image
image

I have one user without capacity and in the drop plan he appers with capacity.

### PR DESCRIPTION
**Pull request by sgtwilko**
Use task colour (Fixes #59), 
Option to Show/Hide non-working days (Fixes #9 , Fixes #57), 
See all team members with capacity (fixes #73), 
Use configured capacity (fixes #111 ), 
Not showing avatar image after D&D fixes.

Also:
Right click on cells to be able to mark/unmark as a Day off for a team member.
Add team setting to enable PBI items to be used on the Drop Plan for teams that do not use Task types.

### CODE REVIEW

**Comment by sgtwilko** [comment]
@yanivsegev I've bumped the version to 2.1.0 as this introduces new functionality.
If you've got any outstanding changes I'm happy to re-work this after you've merged them in.

I'm probably going to start looking at marking days as holiday from the plan next, but would like to chat to see if this aligns with your goals too.

**Comment by sgtwilko** [comment]
@yanivsegev I think I have the days off from the plan working, but DevOps is giving me 503 errors right now, so will push that up tomorrow.

**Comment by sgtwilko** [comment]
@yanivsegev PR updated to include "Mark as Day off" functionality.

**Comment by sgtwilko** [comment]
@yanivsegev PR updated to also include a team wide setting to use PBI level items instead of Task level items on the plan.
Also fixed an issue where the settings page wasn't saving the `highlightPlanningIssues` check box.

**Review by yanivsegev — APPROVED** [review]

**Pull request merged**
