### PR TITLE
Update deps, Add Activity order, add Dark new Theme which supports Az…

### PR DESCRIPTION
**Pull request by sgtwilko**
This started as a couple of tweaks and ended up with a load of changes.
I've bumped the version number to version 2.0.0 as there's quite a few changes.

Changes:

- Update many packages to versions without issues.
- New theme (Modern which adapts light/dark from the currently selected DevOps theme)
- Task progress bar to show how completed a task is based on hours.
- Warnings about out of order tasks
- Settings page to configure new warnings
- Slightly reduce refresh rate when in focus, reduce a lot when the tab is out of focus to stop issues with API limits. #63
- Added Tags and Activities to the search (if you use Development as the activity type this will solve #89 )
 -Fixed Capacity only using the first defined activity type #80
- Disabled LogRocket as it's throwing errors about being over capacity.
- some minor markdown fixes

### CODE REVIEW

**Comment by sgtwilko** [comment]
@yanivsegev Hiya,
I realise life with children can get busy, so if you want I'm happy to fix the build issues if you let me have some access to the build environment, etc.

It may be helpful as there are several other bugs I'd like to fix, and there's a few issues listed here in GitHub I may be able to resolve.
Let me know!

(and I messed up the other PR, so this is the one to work on)

**Comment by sgtwilko** [comment]
I'm also hoping that as this uses a more recent version of the VSS library that it may fix #97  but I can't check that yet.

**Comment by yanivsegev** [comment]
Thank you for all of these wonderful fixes!
I'll try to review and merge them this week!

What else do you need to fix the build issues? (which build issues are you referring to?)

**Comment by sgtwilko** [comment]
Hiya,

> Thank you for all of these wonderful fixes! I'll try to review and merge them this week!
> 

No problem, had a need to change/fix things and wanted to contribute back.


> What else do you need to fix the build issues? (which build issues are you referring to?)

It builds fine for me, bur your PR/ pipeline build is failing.

**Review by yanivsegev — APPROVED** [review]
Great Work! Thank you!

**Comment by sgtwilko** [comment]
Thanks!
I'll probably start working on a couple of other bugs/features shortly.
Would you prefer smaller PRs, one for each thing, or a single larger PR?

**Pull request merged**
